[package]
name = "chizen"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "*"
glam = "*"
egui = "*"

[dependencies.gltf]
version = "*"
features = ["extras", "names"]

[build-dependencies]
bindgen = "*"