[package]
name = "chizen"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "*"
wgpu = "*"
pollster = "*"
bytemuck = { version = "*", features = ["derive"] }
image = { version ="*", features =["png", "jpeg"] }
anyhow = "*"